/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_PWM.h"
#include "M1_IN1_aliases.h"
#include "M1_IN1.h"
#include "M1_IN2_aliases.h"
#include "M1_IN2.h"
#include "M2_IN1_aliases.h"
#include "M2_IN1.h"
#include "M2_IN2_aliases.h"
#include "M2_IN2.h"
#include "LED_4_aliases.h"
#include "LED_4.h"
#include "SEN_4_aliases.h"
#include "SEN_4.h"
#include "SEN_3_aliases.h"
#include "SEN_3.h"
#include "LED_3_aliases.h"
#include "LED_3.h"
#include "LED_2_aliases.h"
#include "LED_2.h"
#include "SEN_2_aliases.h"
#include "SEN_2.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "LED_5_aliases.h"
#include "LED_5.h"
#include "SEN_5_aliases.h"
#include "SEN_5.h"
#include "M2_INV_aliases.h"
#include "M2_INV.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "SEN_1_aliases.h"
#include "SEN_1.h"
#include "M1_INV_aliases.h"
#include "M1_INV.h"
#include "M2_D1_aliases.h"
#include "M2_D1.h"
#include "M1_D1_aliases.h"
#include "M1_D1.h"
#include "SEN_7_aliases.h"
#include "SEN_7.h"
#include "LED_7_aliases.h"
#include "LED_7.h"
#include "SEN_6_aliases.h"
#include "SEN_6.h"
#include "LED_6_aliases.h"
#include "LED_6.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

